	.cpu cortex-a9
	.fpu softvfp
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 2
	.eabi_attribute 34, 1
	.eabi_attribute 18, 4
	.file	"dev-pd-exynos5.c"
	.global	exynos5_device_pd
	.data
	.align	3
	.type	exynos5_device_pd, %object
	.size	exynos5_device_pd, 4320
exynos5_device_pd:
	.word	.LC0
	.word	0
	.space	84
	.word	__compound_literal.1
	.space	248
	.space	16
	.word	.LC0
	.word	1
	.space	84
	.word	__compound_literal.3
	.space	248
	.space	16
	.space	1440
	.word	.LC0
	.word	6
	.space	84
	.word	__compound_literal.5
	.space	248
	.space	16
	.space	360
	.word	.LC0
	.word	8
	.space	84
	.word	__compound_literal.7
	.space	248
	.space	16
	.space	360
	.word	.LC0
	.word	10
	.space	84
	.word	__compound_literal.9
	.space	248
	.space	16
	.word	.LC0
	.word	11
	.space	84
	.word	__compound_literal.11
	.space	248
	.space	16
	.type	__compound_literal.11, %object
	.size	__compound_literal.11, 32
__compound_literal.11:
	.word	exynos_pd_init
	.word	exynos_pd_enable
	.word	exynos_pd_disable
	.space	8
	.word	-31965024
	.word	__compound_literal.10
	.space	4
	.type	__compound_literal.10, %object
	.size	__compound_literal.10, 16
__compound_literal.10:
	.word	-32437976
	.word	-32439780
	.space	8
	.type	__compound_literal.9, %object
	.size	__compound_literal.9, 32
__compound_literal.9:
	.word	exynos_pd_init
	.word	exynos_pd_enable
	.word	exynos_pd_disable
	.space	8
	.word	-31965184
	.word	__compound_literal.8
	.space	4
	.type	__compound_literal.8, %object
	.size	__compound_literal.8, 16
__compound_literal.8:
	.word	-32437984
	.word	-32439780
	.space	8
	.type	__compound_literal.7, %object
	.size	__compound_literal.7, 32
__compound_literal.7:
	.word	exynos_pd_init
	.word	exynos_pd_enable
	.word	exynos_pd_disable
	.space	8
	.word	-31965152
	.word	__compound_literal.6
	.space	4
	.type	__compound_literal.6, %object
	.size	__compound_literal.6, 16
__compound_literal.6:
	.word	0
	.word	-32439780
	.space	8
	.type	__compound_literal.5, %object
	.size	__compound_literal.5, 32
__compound_literal.5:
	.word	exynos_pd_init
	.word	exynos_pd_enable
	.word	exynos_pd_disable
	.space	8
	.word	-31964960
	.word	__compound_literal.4
	.space	4
	.type	__compound_literal.4, %object
	.size	__compound_literal.4, 16
__compound_literal.4:
	.word	-32437940
	.word	-32439780
	.space	8
	.type	__compound_literal.3, %object
	.size	__compound_literal.3, 32
__compound_literal.3:
	.word	exynos_pd_init
	.word	exynos_pd_enable
	.word	exynos_pd_disable
	.space	8
	.word	-31965088
	.word	__compound_literal.2
	.space	4
	.type	__compound_literal.2, %object
	.size	__compound_literal.2, 16
__compound_literal.2:
	.word	-32437968
	.word	-32439780
	.space	8
	.type	__compound_literal.1, %object
	.size	__compound_literal.1, 32
__compound_literal.1:
	.word	exynos_pd_init
	.word	exynos_pd_enable
	.word	exynos_pd_disable
	.space	8
	.word	-31965120
	.word	__compound_literal.0
	.space	4
	.type	__compound_literal.0, %object
	.size	__compound_literal.0, 16
__compound_literal.0:
	.word	-32437972
	.word	-32439780
	.space	8
	.section	.rodata.str1.4,"aMS",%progbits,1
	.align	2
.LC0:
	.ascii	"samsung-pd\000"
	.ident	"GCC: (GNU) 4.8"
